### ISSUE TITLE
Ability to disable or override hover style

### ISSUE THREAD

**Issue by aaronshaf** [DarylBuckle/react-funnel-pipeline#2]
Thanks for creating this library!

**Comment by DarylBuckle** [comment]
Thanks for this suggestion.

You can now do this by upgrading to 0.1.2 where you can now easily override the css classes used in the funnel chart. The hard-coded hover colour which was previously used has been also been removed and instead opacity changes to .7 when hovering.

Example of how to change hover style - add the following to your css;

```css
.funnel-pipeline-chart .funnel-pipeline-chart-row:hover {
  background-color: pink !important;
  opacity: 1 !important;
}
```
