### ISSUE TITLE
Title prop css override

### ISSUE THREAD

**Issue by scho3034** [DarylBuckle/react-funnel-pipeline#6]
Can i override the css for title prop?
It is adding a margin-bottom of 30px by default.

**Comment by DarylBuckle** [comment]
Hi @scho3034 

Unfortunately there isn't currently a prop to override the chart title style attribute. The only way to achieve this at the moment would be to add some css in your style sheet to override it using an !important tag.

E.g

```css
.funnel-pipeline-chart h2 {
  margin-bottom: 0px !important;
}
```

should do the trick.

Let me know otherwise.

Daryl
